#include "sensors.h"
/*
-----------------DO NOT EDIT THIS FILE-----------------
*/

pros::Motor left_motor(9); // Creates a motor on port 9
pros::Motor right_motor(-10);  // Creates a reversed motor on port 10
pros::Optical left_optical(19); // Creates an optical sensor on port 19
pros::Optical right_optical(20); // Creates an optical sensor on port 20

int getLeftOptical() {
	return left_optical.get_hue();
}

int getRightOptical() {
	return right_optical.get_hue();
}

void setLeftMotor(int power) {
	left_motor.move(power);
}

void setRightMotor(int power) {
	right_motor.move(power);
}