#include "sensors.h"
#include <cstdio>
/*
-----------------DO NOT EDIT THIS FILE-----------------
*/

pros::Motor left_motor(9); // Creates a motor on port 9
pros::Motor right_motor(-10);  // Creates a reversed motor on port 10
pros::Optical left_optical(19); // Creates an optical sensor on port 19
pros::Optical right_optical(20); // Creates an optical sensor on port 20

void initSensors() {
	left_optical.set_led_pwm(100);
	right_optical.set_led_pwm(100);

	left_optical.disable_gesture();
	right_optical.disable_gesture();
}

pros::c::optical_raw_s_t getLeftOpticalData() {return left_optical.get_raw();}

pros::c::optical_raw_s_t getRightOpticalData() {return right_optical.get_raw();}

void setLeftMotor(int power) {left_motor.move(power);}

void setRightMotor(int power) {right_motor.move(power);}

void printSensorValues() {
	char buf[48];
	int i = 0;
	while (true) {
		pros::c::optical_raw_s_t l = getLeftOpticalData();
		pros::c::optical_raw_s_t r = getRightOpticalData();

		switch (i++ % 4) {
			case 0:
				snprintf(buf, sizeof(buf), "Red    L=%lu  R=%lu", (unsigned long)l.red, (unsigned long)r.red);
				pros::lcd::set_text(3, buf);
				break;
			case 1:
				snprintf(buf, sizeof(buf), "Green  L=%lu  R=%lu", (unsigned long)l.green, (unsigned long)r.green);
				pros::lcd::set_text(4, buf);
				break;
			case 2:
				snprintf(buf, sizeof(buf), "Blue   L=%lu  R=%lu", (unsigned long)l.blue, (unsigned long)r.blue);
				pros::lcd::set_text(5, buf);
				break;
			case 3:
				snprintf(buf, sizeof(buf), "Clear  L=%lu  R=%lu", (unsigned long)l.clear, (unsigned long)r.clear);
				pros::lcd::set_text(6, buf);
				break;
		}

		pros::delay(20);
	}
}
