#include "sensors.h"
/*
-----------------DO NOT EDIT THIS FILE-----------------
*/

pros::Mutex lcdMutex;

pros::Motor left_motor(9); // Creates a motor on port 9
pros::Motor right_motor(-10);  // Creates a reversed motor on port 10
pros::Optical left_optical(19); // Creates an optical sensor on port 19
pros::Optical right_optical(20); // Creates an optical sensor on port 20

pros::c::optical_raw_s_t getLeftOpticalData() {return left_optical.get_raw();}

pros::c::optical_raw_s_t getRightOpticalData() {return right_optical.get_raw();}

void setLeftMotor(int power) {left_motor.move(power);}

void setRightMotor(int power) {right_motor.move(power);}

void printSensorValues() {
	lcdMutex.take();
	pros::lcd::clear();
	lcdMutex.give();

	while (true) {
		pros::c::optical_raw_s_t leftData = getLeftOpticalData();
		pros::c::optical_raw_s_t rightData = getRightOpticalData();

		lcdMutex.take();
		pros::lcd::print(3, "Red: Left = %d | Right = %d", leftData.red, rightData.red);
		pros::lcd::print(4, "Green: Left = %d | Right = %d", leftData.green, rightData.green);
		pros::lcd::print(5, "Blue: Left = %d | Right = %d", leftData.blue, rightData.blue);
		pros::lcd::print(6, "Clear: Left = %d | Right = %d", leftData.clear, rightData.clear);
		lcdMutex.give();

		pros::delay(20);
	}
}