#include "timer.h"
#include "main.h"
#include <cstdio>
/*
-----------------DO NOT EDIT THIS FILE-----------------
*/

int timerMs = 0;
bool runTimer = false;

static bool seesRed(pros::Optical& sensor) {
    double hue = sensor.get_hue();
    if (hue < 0.0) return false; // sensor errored / not connected
    return hue < 15.0;
}

void startTimer(void* param) {
    runTimer = true;
    timerMs = 0;
    char buf[48];
    while (true) {
        if (master.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_A)) {
            if (runTimer) {
                stopTimer();
            } else {
                runTimer = true;
                timerMs = 0;
            }
        }
        if (runTimer) {
            if (seesRed(left_optical) && seesRed(right_optical)) {
                snprintf(buf, sizeof(buf), "You won in %d.%03d sec", timerMs / 1000, timerMs % 1000);
                pros::lcd::set_text(2, buf);
                runTimer = false;
            } else {
                snprintf(buf, sizeof(buf), "%d.%03d sec", timerMs / 1000, timerMs % 1000);
                pros::lcd::set_text(2, buf);
                timerMs += 20;
            }
        }
        pros::delay(20);
    }
}

void stopTimer() {
    runTimer = false;
    timerMs = 0;
}
