#include "timer.h"
#include "main.h"
#include "sensors.h"
/*
-----------------DO NOT EDIT THIS FILE-----------------
*/

int timerMs = 0;
bool runTimer = false;

void startTimer(void* param) {
    runTimer = true;
    timerMs = 0;
    while (true) {
        if (master.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_A)) {
            if (runTimer) {
                stopTimer();
            } else {
                runTimer = true;
                timerMs = 0;
            }
        }
        if (runTimer) {
            if (getLeftOpticalData().blue > 200 && getRightOpticalData().blue > 200) {
                lcdMutex.take();
                pros::lcd::print(2, "You won in %d.%d sec", timerMs / 1000, timerMs % 1000);
                lcdMutex.give();
                runTimer = false;
            } else {
                lcdMutex.take();
                pros::lcd::print(2, "%d.%d sec", timerMs / 1000, timerMs % 1000);
                lcdMutex.give();
                timerMs += 20;
            }
        }
        pros::delay(20); 
    }
}

void stopTimer() {
    runTimer = false;
    timerMs = 0;
}